# Generated by Django 5.1.7 on 2025-03-07 19:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_original', models.CharField(max_length=255, verbose_name='Оригінальна назва')),
                ('title_english', models.CharField(blank=True, max_length=255, verbose_name='Англійська назва')),
                ('title_ukrainian', models.CharField(max_length=255, verbose_name='Українська назва')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('mal_id', models.IntegerField(blank=True, null=True, verbose_name='MyAnimeList ID')),
                ('description', models.TextField(verbose_name='Опис')),
                ('poster', models.ImageField(upload_to='anime/posters/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='anime/banners/')),
                ('status', models.CharField(choices=[('ongoing', 'Онгоінг'), ('completed', 'Завершено'), ('announced', 'Анонсовано'), ('dropped', 'Покинуто')], default='ongoing', max_length=20, verbose_name='Статус')),
                ('type', models.CharField(choices=[('tv', 'TV Серіал'), ('movie', 'Фільм'), ('ova', 'OVA'), ('ona', 'ONA'), ('special', 'Спешл')], default='tv', max_length=20, verbose_name='Тип')),
                ('year', models.IntegerField(verbose_name='Рік виходу')),
                ('season', models.CharField(blank=True, choices=[('winter', 'Зима'), ('spring', 'Весна'), ('summer', 'Літо'), ('fall', 'Осінь')], max_length=10, null=True, verbose_name='Сезон')),
                ('episodes_count', models.IntegerField(default=0, verbose_name='Кількість епізодів')),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг')),
                ('has_ukrainian_dub', models.BooleanField(default=False, verbose_name='Українська озвучка')),
                ('ukrainian_release_date', models.DateField(blank=True, null=True, verbose_name='Дата виходу українською')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Аніме',
                'verbose_name_plural': 'Аніме',
                'ordering': ['-year', 'title_ukrainian'],
            },
        ),
        migrations.CreateModel(
            name='DubbingStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='dubbing_studios/')),
                ('established_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Студія дубляжу',
                'verbose_name_plural': 'Студії дубляжу',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанри',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnimeScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='anime/screenshots/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='anime.anime')),
            ],
            options={
                'verbose_name': 'Скріншот',
                'verbose_name_plural': 'Скріншоти',
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='dubbing_studios',
            field=models.ManyToManyField(blank=True, related_name='anime', to='anime.dubbingstudio', verbose_name='Студії дубляжу'),
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(related_name='anime', to='anime.genre', verbose_name='Жанри'),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер епізоду')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Назва епізоду')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('duration', models.IntegerField(verbose_name='Тривалість (хв)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='episodes/thumbnails/')),
                ('video_url_1080p', models.URLField(blank=True, verbose_name='Відео 1080p')),
                ('video_url_720p', models.URLField(blank=True, verbose_name='Відео 720p')),
                ('video_url_480p', models.URLField(blank=True, verbose_name='Відео 480p')),
                ('release_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата виходу')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='anime.anime')),
                ('dubbing_studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dubbed_episodes', to='anime.dubbingstudio')),
            ],
            options={
                'verbose_name': 'Епізод',
                'verbose_name_plural': 'Епізоди',
                'ordering': ['anime', 'number'],
                'unique_together': {('anime', 'number')},
            },
        ),
    ]
