# Generated by Django 5.1.7 on 2025-03-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_add_seasons_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['anime', 'season', 'number'], 'verbose_name': 'Епізод', 'verbose_name_plural': 'Епізоди'},
        ),
        migrations.AlterField(
            model_name='anime',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
