# Generated by Django 5.1.7 on 2025-03-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_alter_episode_options_alter_anime_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['anime', 'number'], 'verbose_name': 'Епізод', 'verbose_name_plural': 'Епізоди'},
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('anime', 'number')},
        ),
        migrations.AddField(
            model_name='anime',
            name='duration_per_episode',
            field=models.IntegerField(default=24, verbose_name='Тривалість епізоду (хв)'),
        ),
        migrations.AddField(
            model_name='episode',
            name='is_filler',
            field=models.BooleanField(default=False, verbose_name='Філлер'),
        ),
        migrations.AddField(
            model_name='episode',
            name='is_recap',
            field=models.BooleanField(default=False, verbose_name='Рекап'),
        ),
        migrations.AddField(
            model_name='episode',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Оцінка'),
        ),
        migrations.AddField(
            model_name='episode',
            name='title_japanese',
            field=models.CharField(blank=True, max_length=255, verbose_name='Японська назва епізоду'),
        ),
        migrations.AddField(
            model_name='episode',
            name='title_romanji',
            field=models.CharField(blank=True, max_length=255, verbose_name='Романізована назва епізоду'),
        ),
        migrations.RemoveField(
            model_name='episode',
            name='season',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
