# Generated by Django 5.1.7 on 2025-03-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_alter_episode_options_alter_episode_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='name_ukrainian',
            field=models.CharField(blank=True, max_length=100, verbose_name='Українська назва'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Оригінальна назва'),
        ),
    ]
